config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: "dashboard#index"

  resources :managements
  resources :infractions
  resources :notifications
  resources :laws
  resources :users

  resources :setup

  get 'notifications/:id/print', to: 'notifications#print'

  get '/supervisions/infractions'        , to: 'supervisions#infractions'
  get '/supervisions/infractions/:id'    , to: 'supervisions#infractions_show'
  get '/infractions/:id/supervisions/new', to: 'supervisions#new'

  delete '/fines/:id', to: 'supervision/infractions#delete_fine'

  post '/infraction/generate/notification',    to: 'infractions#generate_notification', as: 'generate_notification'
  get '/infraction/:id/generate/assessments' , to: 'infractions#generate_assessment', as: 'generate_assessments'

  resources :supervisions
  # namespace :supervision do
  #   resources :infractions
  #   resources :assessments
  #
  #   get '/assessments/:id/generate', to: 'assessments#update', as: 'generate_assessment'
  # end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  def index
    @notifications = Notification.all
  end

  def new
    @notification = Notification.new
  end

  def edit
    @notification = Notification.find(params[:id])
    @fine         = Fine.where(notification_id: params[:id])
  end

  def show
    @infraction = set_notification
    @fine         = Fine.find_by(infraction_id: params[:id])
  end

  def create
    notification = notification_params.merge({state: :notified})
    laws         = params.delete(:laws)

    @notification = Supervision::Notification.new(notification)

    laws.each do |law|
      Fine.create(notification_id: @notification.id, law_id: law)
    end

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notifications_path }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    notification = notification_params
    laws         = params.delete(:laws)

    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to supervision_notifications_path }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end

    if laws
      laws.each do |law|
        Fine.create(notification_id: @notification.id, law_id: law)
      end
    end
  end

  def print
    @infraction = set_notification
    @fine       = Fine.find_by(infraction_id: params[:id])
    render "notifications/print", layout: false
  end

  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to supervision_notifications_path }
      format.json { head :no_content }
    end
  end

  def delete_fine
    Fine.find(params[:id]).destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Infraction.find(params[:id])
  end

  def notification_params
      params.require(:supervision_notification).permit(
        :owner_name,
        :owner_identifier,
        :owner_zip_code,
        :owner_address,
        :owner_address_number,
        :owner_address_complement,
        :owner_district,
        :owner_city,
        :owner_state,
        :owner_ddd_mobile,
        :owner_mobile,
        :owner_ddd_phone,
        :owner_phone,
        :property_zone,
        :property_zip_code,
        :property_address,
        :property_address_number,
        :property_address_complement,
        :property_district,
        :property_city,
        :property_state,
        :property_meter,
        :property_block,
        :property_allotment,
        :property_observation,
        :notify_description);
  end
end

app/views/notifications/edit.html.erb
<h>Fiscalização | Notificação</h>
<div class="panel">
 <%= form_for(@notification, url: notification_path(@notification), :method=>:put) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="sub_title">
        <div class="pull-left">Dados do proprietário</div>
        <div class="pull-right">
          <div class="radio-inline">
            <label><input type="radio" checked="checked">Pessoa Fisica</label>
          </div>

          <div class="radio-inline">
            <label><input type="radio" >Pessoa Juridica</label>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-7">
      <%= f.label :owner_name, class: "control-label" %>
      <%= f.text_field :owner_name, autofocus: true, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :owner_identifier, class: "control-label" %>
      <%= f.text_field :owner_identifier, class: "form-control" %>
    </div>

    <div class="col-sm-2">
      <%= f.label :owner_zip_code, class: "control-label" %>
      <%= f.text_field :owner_zip_code, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-5">
      <%= f.label :owner_address, class: "control-label" %>
      <%= f.text_field :owner_address, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :owner_address_number, class: "control-label" %>
      <%= f.text_field :owner_address_number, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :owner_address_complement, class: "control-label" %>
      <%= f.text_field :owner_address_complement, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :owner_district, class: "control-label" %>
      <%= f.text_field :owner_district, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <%= f.label :owner_city, class: "control-label" %>
      <%= f.text_field :owner_city, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :owner_state, class: "control-label" %>
      <%= f.text_field :owner_state, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :owner_ddd_mobile, class: "control-label" %>
      <%= f.text_field :owner_ddd_mobile, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :owner_mobile, class: "control-label" %>
      <%= f.text_field :owner_mobile, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :owner_ddd_phone, class: "control-label" %>
      <%= f.text_field :owner_ddd_phone, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :owner_phone, class: "control-label" %>
      <%= f.text_field :owner_phone, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="sub_title">
        <div class="pull-left">Dados do Imóvel</div>
        <div class="pull-right">
          <div class="radio-inline">
            <label><%= f.radio_button(:property_zone, "Urban", checked: true) %>Área Urbana</label>
          </div>

          <div class="radio-inline">
            <label><%= f.radio_button(:property_zone, "Rural") %>Área Rural</label>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <%= f.label :property_zip_code, class: "control-label" %>
      <%= f.text_field :property_zip_code, class: "form-control" %>
    </div>

    <div class="col-sm-9">
      <%= f.label :property_address, class: "control-label" %>
      <%= f.text_field :property_address, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :property_address_number, class: "control-label" %>
      <%= f.text_field :property_address_number, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <%= f.label :property_address_complement, class: "control-label" %>
      <%= f.text_field :property_address_complement, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :property_district, class: "control-label" %>
      <%= f.text_field :property_district, class: "form-control" %>
    </div>

    <div class="col-sm-3">
      <%= f.label :property_city, class: "control-label" %>
      <%= f.text_field :property_city, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :property_state, class: "control-label" %>
      <%= f.text_field :property_state, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :property_meter, class: "control-label" %>
      <%= f.text_field :property_meter, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :property_block, class: "control-label" %>
      <%= f.text_field :property_block, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :property_allotment, class: "control-label" %>
      <%= f.text_field :property_allotment, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= f.label :property_observation, class: "control-label" %>
      <%= f.text_area :property_observation, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="sub_title">Imagens</div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-md-3">
      <a href="#" class="thumbnail">
        <img data-src="holder.js/100%x180" alt="100%x180" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjU5LjU1NDY4NzUiIHk9IjkwIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MTcxeDE4MDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
      </a>
    </div>

    <div class="col-xs-6 col-md-3">
      <a href="#" class="thumbnail">
        <img data-src="holder.js/100%x180" alt="100%x180" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjU5LjU1NDY4NzUiIHk9IjkwIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MTcxeDE4MDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
      </a>
    </div>

    <div class="col-xs-6 col-md-3">
      <a href="#" class="thumbnail">
        <img data-src="holder.js/100%x180" alt="100%x180" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjU5LjU1NDY4NzUiIHk9IjkwIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MTcxeDE4MDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
      </a>
    </div>

    <div class="col-xs-6 col-md-3">
      <a href="#" class="thumbnail">
        <img data-src="holder.js/100%x180" alt="100%x180" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjU5LjU1NDY4NzUiIHk9IjkwIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MTcxeDE4MDwvdGV4dD48L2c+PC9zdmc+" data-holder-rendered="true" style="height: 280px; width: 100%; display: block;">
      </a>
    </div>
  </div>

<div class="row">
  <div class="col-sm-12">
    <div class="sub_title">Penalidades</div>
  </div>
</div>

<div class="col-sm-12">
  <div class="row">
    <%= f.label :notify_description, class: "control-label" %>
    <%= f.text_area :notify_description, class: "form-control text_area" %>
  </div>
</div>

<div class="col-sm-12">
  <div class="row">
    <%= f.label 'Conforme lei', class: "control-label" %>
    <table class="table">
      <tbody>
        <% @fine.each do | fine | %>
        <tr>
          <td width='2%' id='delete_fine' style="cursor:pointer">
            <i id=<%= fine.id %> class="fa fa-trash-o"></i>
          </td>
          <td colspan="3"><%= fine.law.description %></td>
        </tr>
        <% end %>

        <%  fine = Fine.all.pluck(:law_id) %>
        <%  Law.where.not(id: fine).each do | law | %>
        <tr>
          <td><input value=<%= law.id %> type="checkbox" name="laws[]"></td>
          <td width="100">Lei: <%= law.number %></td>
          <td width="80">Artigo: <%= law.article %></td>
          <td><%= law.description %></td>
        </tr>
        <% end %>

        <% Law.where.not(id: @fine.pluck(:law_id) ).each do | law | %>
        <tr>
          <td><input value=<%= law.id %> type="checkbox" name="laws[]"></td>
          <td width="100">Lei: <%= law.number %></td>
          <td width="80">Artigo: <%= law.article %></td>
          <td><%= law.description %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-sm-2  pull-right">
    <label>
      Prazo de regularização
    </label>
    <input type="text" name='regulation' class="form-control">
  </div>
</div>

  <div class="panel-footer">
    <div class="actions">
      <button class="btn btn-primary">Atualizar</button>
      <button class="btn btn-warning">Gerar Autuação</button>
    </div>

    <div class="actions pull-left">
      <%= link_to f.button("Voltar", class: "btn"), notifications_path %>
    </div>
  </div>
<% end %>
</div>
<script src='/assets/fines.js'></script>

app/views/notifications/show.html.erb
<style media="screen">
.notification-view{
  border: 1px solid gray;
  padding: 8px;
}
</style>
<div class="container" style="width: 950px;">
  <div class="block-header">
    <ul class="actions">
      <div class="btn-action-new">
        <%= link_to 'Imprimir'.html_safe, "/notifications/2/print", class: "btn btn-sm btn-primary full btnPrint"%>
        <%= link_to 'Salvar PDF'.html_safe, "/infractions/", class: "btn btn-sm btn-primary full" %>
        <%= link_to 'Autuar'.html_safe, "/infractions/", class: "btn btn-sm btn-danger full" %>
      </div>
    </ul>
    <h2>
      <a href="/" title="voltar">
        <i class="zmdi zmdi-long-arrow-left zmdi-hc-lg"></i>
      </a> Notificação
    </h2>
  </div>

  <div class="card">
    <div class="card-body card-padding">
      <div class="row">
        <div class="col-sm-10"></div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-9 notification-view">
          <div class="col-sm-10 ">
            <h3><b>AUTO DE INFRAÇÃO</b></h3>
            <strong><small>IMPOSIÇÃO DE PENALIDADE DE MULTA</small></strong>
          </div>
        </div>

        <div class="col-sm-2 pull-right notification-view">
          <small>Data:</small><br>
          <strong><%= Time.now.strftime("%d/%m/%Y") %></strong>
          <br>
          <small>Processo Nº</small><br>
          <strong><%= @infraction.id.to_s.rjust(6, '0') %></strong>
        </div>
      </div>
      <br>
      <div class="row">
        Idendificação do infrator
        <div class="col-sm-12 notification-view">

          <div class="col-sm-10 ">
            <small>Nome</small></br>
            <strong><%= @infraction.owner_name.upcase %></strong>
          </div>
          <div class="col-sm-2">
            <small>Identificação</small></br>
            <strong><%= @infraction.owner_identifier %></strong>
          </div>
          <div class="col-sm-2">
            <small>Celular</small></br>
            <strong><%= @infraction.owner_mobile %></strong>
          </div>
          <div class="col-sm-2">
            <small>Telefone</small></br>
            <strong><%= @infraction.owner_phone %></strong>
          </div>

          <div class="col-sm-4">
            <small>Logadouro</small></br>
            <strong><%= @infraction.owner_address.upcase %></strong>
          </div>

          <div class="col-sm-2">
            <small>Numero</small></br>
            <strong><%= @infraction.owner_address_number %></strong>
          </div>


          <div class="col-sm-2">
            <small>Bairro</small></br>
            <strong><%= @infraction.owner_district.upcase %></strong>
          </div>

          <div class="col-sm-2">
            <small>CEP</small></br>
            <strong><%= @infraction.owner_zip_code %></strong>
          </div>

          <div class="col-sm-2">
            <small>Municipio</small></br>
            <strong><%= @infraction.owner_city.upcase %></strong>
          </div>
        </div>

      </div>

      <br>
      <div class="row">
        Idendificação do Imóvel
        <div class="col-sm-12 notification-view">
          <div class="col-sm-4">
            <small>Logadouro</small></br>
            <strong><%= @infraction.property_address.upcase %></strong>
          </div>

          <div class="col-sm-2">
            <small>Numero</small></br>
            <strong><%= @infraction.property_address_number %></strong>
          </div>

          <div class="col-sm-2">
            <small>Complemento</small></br>
            <strong><%= @infraction.property_address_complement.upcase %></strong>
          </div>

          <div class="col-sm-2">
            <small>CEP</small></br>
            <strong><%= @infraction.property_zip_code %></strong>
          </div>

          <div class="col-sm-2">
            <small>Zona</small></br>
            <strong><%= @infraction.property_zone %></strong>
          </div>
          <div class="col-sm-2">
            <small>Bairro</small></br>
            <strong><%= @infraction.property_district.upcase   %></strong>
          </div>

          <div class="col-sm-2">
            <small>Municipio</small></br>
            <strong><%= @infraction.property_city.upcase %></strong>
          </div>

          <div class="col-sm-2">
            <small>Estado</small></br>
            <strong><%= @infraction.property_state.upcase %></strong>
          </div>

          <div class="col-sm-2">
            <small>M2</small></br>
            <strong><%= @infraction.property_meter %></strong>
          </div>

          <div class="col-sm-2">
            <small>Quadra</small></br>
            <strong><%= @infraction.property_block %></strong>
          </div>

          <div class="col-sm-2">
            <small>Lote</small></br>
            <strong><%= @infraction.property_allotment %></strong>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        Observações
        <div class="col-sm-12 notification-view">
          <div class="col-sm-12">
            <strong><%= @infraction.property_observation.upcase %></strong>
          </div>
        </div>
      </div>

      <br>
      <div class="row">
        Irregularidades
        <div class="col-sm-12 notification-view">
          <% @infraction.fine.each do | fine |%>
          <div class="row">
            <div class="col-sm-2">
              <small>Data da Infração</small></br>
              <strong><%= @infraction.created_at.strftime("%d/%m/%Y") %></strong>
            </div>

            <div class="col-sm-2">
              <small>Hora da Infração</small></br>
              <strong><%= @infraction.created_at.strftime("%H:%M") %></strong>
            </div>

            <div class="col-sm-2">
              <small>Conforme Lei</small></br>
              <strong>Nº: <%= fine.law.number %></strong>
            </div>

            <div class="col-sm-2">
              <small>Artigo</small></br>
              <strong><%= fine.law.article %></strong>
            </div>

            <div class="col-sm-2">
              <small>Multa</small></br>
              <strong>R$ <%= fine.price %></strong>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12">
              <small>Enquadramento</small></br>
              <strong><%= fine.law.description %></strong>
            </div>
          </div>
          <hr>
          <% end %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-12 notification-view">
          <div class="col-sm-10">
            <small>Descrição da Infração</small></br>
            <strong><%= @infraction.notify_description.upcase %></strong>
          </div>

          <div class="colcol-sm-2">
            <small>Valor Total da Multa</small><br>

          </div>
        </div>
      </div>
      <br>
      <div class="row">
        Fiscalização
        <div class="col-sm-12 notification-view">
          <% if not @infraction.supervision.count.zero? %>
          <% @infraction.supervision.each do |supervision|%>
          <div class="col-sm-2">
            <small>Fiscalizado Em:</small></br>
            <strong><%= supervision.created_at.strftime("%d/%m") %></strong>
          </div>
          <div class="col-sm-2">
            <small>As:</small></br>
            <strong><%= supervision.created_at.strftime("%H:%M") %> hs</strong>
          </div>
          <div class="col-sm-8">
            <small>Descrição:</small></br>
            <strong><%= supervision.observation  %></strong>
          </div>
          <% end %>
          <% else %>
          <div class="well" align="center">Não ha m laudo de infração referente a esta infração</div>
          <% end %>
        </div>
      </div>
      <br>
      <div class="row">
        Unidade Emitente
        <div class="col-sm-12 notification-view">
          <div class="col-sm-8" style="margin-top:10px">
            Prefeitura Municipal de Assis<br>
            Secretaria Municipal de Meio Ambiente<br>
            Departamento de Fiscalização Ambiental
          </div>

          <div class="col-sm-4" style="margin-top:40px" align="center">
            ____________________________________<br>
            assinatura
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        Ciência do Infrator
        <div class="col-sm-12 notification-view">
          <div class="col-sm-8" style="height:60px">
            <small>Nome:</small></br>

          </div>

          <div class="col-sm-8">
            <small>Data:</small></br>

          </div>

          <div class="col-sm-4" align="center">
            ____________________________________<br>
            assinatura
          </div>
        </div>
      </div>
      <hr>
      <div class="text-right">
        <%= link_to "Voltar", infractions_path, class: "btn btn-link waves-effect" %>
      </div>
    </div>
  </div>