config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: "dashboard#index"

  resources :managements
  resources :infractions
  resources :notifications
  resources :laws
  resources :users

  resources :setup

  get 'notifications/:id/print', to: 'notifications#print'

  get '/supervisions/infractions'        , to: 'supervisions#infractions'
  get '/supervisions/infractions/:id'    , to: 'supervisions#infractions_show'
  get '/infractions/:id/supervisions/new', to: 'supervisions#new'

  delete '/fines/:id', to: 'supervision/infractions#delete_fine'

  post '/infraction/generate/notification',    to: 'infractions#generate_notification', as: 'generate_notification'
  get '/infraction/:id/generate/assessments' , to: 'infractions#generate_assessment', as: 'generate_assessments'

  resources :supervisions
  # namespace :supervision do
  #   resources :infractions
  #   resources :assessments
  #
  #   get '/assessments/:id/generate', to: 'assessments#update', as: 'generate_assessment'
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :management
  has_many :infractions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.valid_password?(user_params[:current_password])
      if  not params[:user][:password].empty?
        if params[:user][:password] == params[:user][:password_confirmation]
          user = user_params
          user.delete(:current_password)
          @user.update_attributes(user)
        end
      else
        user = user_params_change_password
        user.delete(:current_password)
        user.delete(:password)
        user.delete(:password_confirmation)
        @user.update_attributes(user)
      end
    end

    if not @user.errors.count.zero?
      render :edit
    else
      redirect_to action: "index"
    end
  end

  def create
    debugger
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit( :name, :email, :current_password, :avatar_cache, :avatar, :user_type, :management_id);
  end

  def user_params_change_password
    params.require(:user).permit( :name, :email, :password, :password_confirmation, :current_password, :avatar_cache, :avatar, :user_type, :management_id);
  end
end

app/views/users/edit.html.erb
<div class="block-header">
  <h2>
    <a href="/" title="voltar">
      <i class="zmdi zmdi-long-arrow-left zmdi-hc-lg"></i>
    </a> Editar Usuário
  </h2>
</div>

<%= form_for(@user, url: user_path(@user), :method=>:put) do |f| %>
<div class="card">
  <div class="card-body card-padding">
    <div class="row">
      <div class="col-sm-5">
        <div class="form-group fg-line fg-line">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-5">
        <div class="form-group fg-line fg-line">
          <%= f.label :email, class: "control-label" %>
          <%= f.email_field :email, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="form-group fg-line fg-line">
          <%= f.label :user_type, class: "control-label" %>
          <%= f.select(:user_type, options_for_select([["Administrador","administrator"],["Fiscal","fiscal"]]),{}, class: "form-control") %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4">
        <div class="form-group fg-line fg-line">
          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group fg-line fg-line">
          <%= f.label :password_confirmation, class: "control-label" %>
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group fg-line fg-line">
          <%= f.label :current_password, class: "control-label" %>
          <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group fg-line fg-line">
          <%= f.label :management, class: "control-label" %><br />
          <%= f.select :management_id, options_for_select(Management.all.map{|s|[s.name, s.id]}), {}, class: "form-control " %>
        </div>
      </div>
    </div>

    <div class="pull-right">
      <%= link_to "Voltar", users_path, class: "btn btn-link waves-effect" %>
      <button class="btn bgm-orange waves-effect"> Salvar</button>
    </div>
    <div class="clearfix"></div>
  </div>
  <% end %>

app/views/users/index.html.erb
<div class="block-header">
  <ul class="actions">
    <div class="btn-action-new">
    <%= link_to '<i class="fa fa-plus"></i> <b>Novo Usuário</b>'.html_safe, new_user_path, class: "btn btn-primary btn-sm" %>
    </div>
  </ul>
  <h2>
    <a href="/" title="voltar">
      <i class="zmdi zmdi-long-arrow-left zmdi-hc-lg"></i>
    </a> Usuários
  </h2>
</div>

<div class="card">
  <div class="card-body card-padding">

    <table id="table-user" class="table display">
      <thead class="table-heading">
      <tr>
        <th width="30%">Name</th>
        <th width="30%">E-mail</th>
        <th width="20%">Tipo</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do | user |  %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.user_type %></td>
          <td align="center">
          <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_user_path(user), class: "btn btn-primary btn-sm" %>
            <button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i> Remover</button>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function() {
    var table = $('#table-user').dataTable({ "dom": '<tp>' });
  } );
</script>

app/views/users/new.html.erb
<div class="block-header">
  <h2>
    <a href="/" title="voltar">
      <i class="zmdi zmdi-long-arrow-left zmdi-hc-lg"></i>
    </a> Dados do Usuário
  </h2>
</div>

<%= form_for('user', url: registration_path('user'), :html => {:multipart => true}) do |f| %>
<div class="card">
  <div class="card-body card-padding">
    <div class="row">
      <div class="col-sm-8">
        <div class="form-group fg-line fg-line">
          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="form-group fg-line fg-line">
          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
      </div>

      <div class="col-sm-2">
        <div class="form-group fg-line fg-line">
          <%= f.label :password_confirmation, class: "control-label" %>
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col-sm-8">
        <div class="form-group fg-line fg-line">
          <%= f.label :email, class: "control-label" %>
          <%= f.email_field :email, autofocus: true, class: "form-control" %>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group fg-line fg-line">
          <%= f.label :user_type, class: "control-label" %>
          <%= f.select(:user_type, options_for_select([["Administrador","administrator"],["Fiscal","fiscal"]]),{}, class: "form-control") %>
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group fg-line fg-line">
          <%= f.label :management, class: "control-label" %><br />
          <%= f.select :management_id, options_for_select(Management.all.map{|s|[s.name, s.id]}), {}, class: "form-control " %>
        </div>
      </div>
    </div>

    <div class="pull-right">
      <%= link_to "Voltar", users_path, class: "btn btn-link waves-effect" %>
      <%= f.button "Salvar", class: "btn bgm-orange waves-effect"  %>
    </div>
    <div class="clearfix"></div>
  </div>
  <% end %>