config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: "dashboard#index"

  resources :managements
  resources :infractions
  resources :notifications
  resources :laws
  resources :users

  resources :setup

  get 'notifications/:id/print', to: 'notifications#print'

  get '/supervisions/infractions'        , to: 'supervisions#infractions'
  get '/supervisions/infractions/:id'    , to: 'supervisions#infractions_show'
  get '/infractions/:id/supervisions/new', to: 'supervisions#new'

  delete '/fines/:id', to: 'supervision/infractions#delete_fine'

  post '/infraction/generate/notification',    to: 'infractions#generate_notification', as: 'generate_notification'
  get '/infraction/:id/generate/assessments' , to: 'infractions#generate_assessment', as: 'generate_assessments'

  resources :supervisions
  # namespace :supervision do
  #   resources :infractions
  #   resources :assessments
  #
  #   get '/assessments/:id/generate', to: 'assessments#update', as: 'generate_assessment'
  # end
end

app/models/supervision.rb
class Supervision < ActiveRecord::Base
  belongs_to :infraction
end

app/controllers/supervisions_controller.rb
class SupervisionsController < ApplicationController
  before_action :set_supervision, only: [:show, :edit, :update, :destroy]

  # GET /supervisions
  # GET /supervisions.json
  def index
    @supervisions = Supervision.all
  end

  # GET /supervisions/1
  # GET /supervisions/1.json
  def show
  end

  # GET /supervisions/new
  def new
    @supervision  = Supervision.new
    @supervision.infraction_id = params[:id]
    render layout: false
  end

  # GET /supervisions/1/edit
  def edit
  end

  # POST /supervisions
  # POST /supervisions.json
  def create
    @supervision = Supervision.new(supervision_params)
    @infraction = Infraction.find(supervision_params[:infraction_id])
    respond_to do |format|
      if @supervision.save
        if supervision_params[:status] === 'proceeds'
          @infraction.supervised!
        else
          @infraction.archived!
        end
        format.html { redirect_to infractions_path, success: 'Laudo de fiscalização cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @supervision }
      else
        format.html { render :new }
        format.json { render json: @supervision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supervisions/1
  # PATCH/PUT /supervisions/1.json
  def update
    respond_to do |format|
      if @supervision.update(supervision_params)
        format.html { redirect_to @supervision, notice: 'Supervision was successfully updated.' }
        format.json { render :show, status: :ok, location: @supervision }
      else
        format.html { render :edit }
        format.json { render json: @supervision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supervisions/1
  # DELETE /supervisions/1.json
  def destroy
    @supervision.destroy
    respond_to do |format|
      format.html { redirect_to supervisions_url, notice: 'Supervision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def infractions
    @infractions = Infraction.all
    render  "supervisions/infractions/index"
  end

  def infractions_show
    @infraction = Infraction.find(params[:id])
    @fine         = Fine.find_by(infraction_id: params[:id])
    render  "supervisions/infractions/show", layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supervision
      @supervision = Supervision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supervision_params
      params.require(:supervision).permit(:infraction_id, :observation, :status)
    end
end

app/helpers/supervisions_helper.rb
module SupervisionsHelper
end

app/views/supervisions/edit.html.erb
<h1>Editing Supervision</h1>

<%= render 'form' %>

<%= link_to 'Show', @supervision %> |
<%= link_to 'Back', supervisions_path %>

app/views/supervisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Supervisions</h1>

<table>
  <thead>
    <tr>
      <th>Notification</th>
      <th>Observation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supervisions.each do |supervision| %>
      <tr>
        <td><%= supervision.infraction %></td>
        <td><%= supervision.observation %></td>
        <td><%= link_to 'Show', supervision %></td>
        <td><%= link_to 'Edit', edit_supervision_path(supervision) %></td>
        <td><%= link_to 'Destroy', supervision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supervision', new_supervision_path %>

app/views/supervisions/new.html.erb
<div class="row">
<%= form_for(@supervision) do |f| %>
  <div class="field">
    <%= f.text_field :infraction_id, class: "form-control hidden",rows: 10 %>    
    <%= f.label :observation, class: "control-label" %><br>
    <%= f.text_area :observation, class: "form-control",rows: 10 %>
  </div>
  <div class="actions">
    <%= f.submit("Enviar", class: "btn btn-primary") %>
  </div>
<% end %>
</div>

app/views/supervisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notification:</strong>
  <%= @supervision.notification %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @supervision.observation %>
</p>

<%= link_to 'Edit', edit_supervision_path(@supervision) %> |
<%= link_to 'Back', supervisions_path %>