config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root to: "dashboard#index"

  resources :managements
  resources :infractions
  resources :notifications
  resources :laws
  resources :users

  resources :setup

  get 'notifications/:id/print', to: 'notifications#print'

  get '/supervisions/infractions'        , to: 'supervisions#infractions'
  get '/supervisions/infractions/:id'    , to: 'supervisions#infractions_show'
  get '/infractions/:id/supervisions/new', to: 'supervisions#new'

  delete '/fines/:id', to: 'supervision/infractions#delete_fine'

  post '/infraction/generate/notification',    to: 'infractions#generate_notification', as: 'generate_notification'
  get '/infraction/:id/generate/assessments' , to: 'infractions#generate_assessment', as: 'generate_assessments'

  resources :supervisions
  # namespace :supervision do
  #   resources :infractions
  #   resources :assessments
  #
  #   get '/assessments/:id/generate', to: 'assessments#update', as: 'generate_assessment'
  # end
end

app/models/management.rb
class Management < ActiveRecord::Base
  has_many :users

  mount_uploader :avatar, AvatarUploader
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :set_management, only: [:show, :edit, :update, :destroy]

  # GET /managements
  # GET /managements.json
  def index
    @managements = Management.all
  end

  # GET /managements/1
  # GET /managements/1.json
  def show
  end

  # GET /managements/new
  def new
    @management = Management.new
  end

  # GET /managements/1/edit
  def edit
  end

  # POST /managements
  # POST /managements.json
  def create
    @management = Management.new(management_params)
    respond_to do |format|
      if @management.save
        format.html { redirect_to @management, notice: 'Management was successfully created.' }
        format.json { render :show, status: :created, location: @management }
      else
        format.html { render :new }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managements/1
  # PATCH/PUT /managements/1.json
  def update
    respond_to do |format|
      if @management.update(management_params)
        format.html { redirect_to @management, notice: 'Management was successfully updated.' }
        format.json { render :show, status: :ok, location: @management }
      else
        format.html { render :edit }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managements/1
  # DELETE /managements/1.json
  def destroy
    @management.destroy
    respond_to do |format|
      format.html { redirect_to managements_url, notice: 'Management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_management
      @management = Management.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def management_params
      params.require(:management).permit(:name, :prefecture, :zip_code, :address, :address_number, :district, :city, :state, :phone)
    end
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/managements/_form.html.erb
<%= form_for(@management) do |f| %>
  <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% @management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prefecture %><br>
    <%= f.text_field :prefecture %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address_number %><br>
    <%= f.text_field :address_number %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.text_field :district %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managements/_form_new.erb
<div class="form-group">
  <%= form_for(@management) do |f| %>
  <div class="row">
    <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>
      <ul>
        <% @management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="col-sm-2" style="padding: 0px;">
      <div class="row">
        <div class="sub_title">Brazão</div>
        <%= image_tag(@management.avatar.url, style: "width: 100%") %>
        <span class="btn btn-primary btn-sm btn-file", style="width: 100%">
          Escolha um foto <%=  f.file_field :avatar %>
          <%=  f.hidden_field :avatar_cache %>
        </span>
      </div>
    </div>

    <div class="col-sm-10" style="padding: 0px;">
      <div class="col-sm-12">
        <%= f.label :name, class: "control-label"%><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-sm-12">
        <%= f.label :prefecture, class: "control-label"%><br>
        <%= f.text_field :prefecture, class: "form-control" %>
      </div>
      <div class="col-sm-12">
        <%= f.label :address, class: "control-label"%><br>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="col-sm-2">
        <%= f.label :address_number, class: "control-label"%><br>
        <%= f.text_field :address_number, class: "form-control" %>
      </div>
      <div class="col-sm-2">
        <%= f.label :zip_code, class: "control-label"%><br>
        <%= f.text_field :zip_code, class: "form-control" %>
      </div>
      <div class="col-sm-2">
        <%= f.label :district, class: "control-label"%><br>
        <%= f.text_field :district, class: "form-control" %>
      </div>
      <div class="col-sm-3">
        <%= f.label :state, class: "control-label"%><br>
        <%= f.text_field :state, class: "form-control" %>
      </div>
      <div class="col-sm-3">
        <%= f.label :phone, class: "control-label"%><br>
        <%= f.text_field :phone, class: "form-control" %>
      </div>
    </div>

  </div>
  <div class="panel-footer">
    <div class="actions">
      <%= f.submit "Adicionar", class: "btn btn-primary"  %>
    </div>

    <div class="actions pull-left">
      <%= link_to f.button("Voltar", class: "btn"), managements_path %>
    </div>
  </div>
  <% end %>
</div>

app/views/managements/_form_setup_new.erb
  <div class="form-group">
<%= form_for(@management) do |f| %>
<div class="row">
  <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>
      <ul>
      <% @management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-2" style="padding: 0px;">
    <div class="row">
      <div class="sub_title">Brazão</div>
      <%= image_tag(@management.avatar.url, style: "width: 100%") %>
      <span class="btn btn-primary btn-sm btn-file", style="width: 100%">
        Escolha um foto <%=  f.file_field :avatar %>
        <%=  f.hidden_field :avatar_cache %>
      </span>
    </div>
  </div>

  <div class="col-sm-10" style="padding: 0px;">
  <div class="col-sm-12">
    <%= f.label :name, class: "control-label"%><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="col-sm-12">
    <%= f.label :prefecture, class: "control-label"%><br>
    <%= f.text_field :prefecture, class: "form-control" %>
  </div>
  <div class="col-sm-12">
    <%= f.label :address, class: "control-label"%><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="col-sm-2">
    <%= f.label :address_number, class: "control-label"%><br>
    <%= f.text_field :address_number, class: "form-control" %>
  </div>
  <div class="col-sm-2">
    <%= f.label :zip_code, class: "control-label"%><br>
    <%= f.text_field :zip_code, class: "form-control" %>
  </div>
  <div class="col-sm-2">
    <%= f.label :district, class: "control-label"%><br>
    <%= f.text_field :district, class: "form-control" %>
  </div>
  <div class="col-sm-3">
    <%= f.label :state, class: "control-label"%><br>
    <%= f.text_field :state, class: "form-control" %>
  </div>
  <div class="col-sm-3">
    <%= f.label :phone, class: "control-label"%><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
</div>

</div>

    <div class="actions">
      <%= f.submit "Adicionar", class: "btn btn-primary"  %>
    </div>

    <div class="actions pull-left">
      <%= link_to f.button("Voltar", class: "btn"), managements_path %>
    </div>
<% end %>
</div>

app/views/managements/edit.html.erb
<h1>Editing Management</h1>

<%= render 'form' %>

<%= link_to 'Show', @management %> |
<%= link_to 'Back', managements_path %>

app/views/managements/index.html.erb
<h><div class="col-sm-2 title">Unidade</div>
  <div id="actin-btn" class="pull-right">
    <%= link_to '<i class="fa fa-plus"></i> <b>Nova Unidade</b>'.html_safe, new_management_path, class: "btn btn-primary btn-sm" %>
  </div>
</h>

<div class="form-group">
  <div class="row">
    <table  id="table-managements" class="table table-striped display">
      <thead class="table-heading">
        <tr>
          <th width="auto">Name</th>
          <th width="auto">Prefecture</th>
          <th width="auto">State</th>
          <th width="auto">Phone</th>
          <th width="10%">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @managements.each do |management| %>
        <tr>
          <td><%= management.name %></td>
          <td><%= management.prefecture %></td>
          <td><%= management.state %></td>
          <td><%= management.phone %></td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-sm" data-toggle="dropdown"><i class="fa fa-plus"></i> Ações</button>
              <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class="caret"></span>
              </button>

              <ul class="dropdown-menu" role="menu">
                <li><%= link_to '<i class="fa fa-search"></i> Visualizar'.html_safe, management %></li>
                <li><%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_management_path(management) %></li>
                <li><%= link_to '<i class="fa fa-trash-o"></i> Deletar'.html_safe, management, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
$(document).ready(function() {
  var table = $('#table-managements').dataTable({ "dom": '<tp>' });
});
</script>

app/views/managements/new.html.erb
<%=
if Management.all.count.zero?
  render 'form_setup_new'
else
  render 'form_new'
end
 %>

app/views/managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @management.name %>
</p>

<p>
  <strong>Prefecture:</strong>
  <%= @management.prefecture %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @management.zip_code %>
</p>

<p>
  <strong>Address:</strong>
  <%= @management.address %>
</p>

<p>
  <strong>Address number:</strong>
  <%= @management.address_number %>
</p>

<p>
  <strong>District:</strong>
  <%= @management.district %>
</p>

<p>
  <strong>City:</strong>
  <%= @management.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @management.state %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @management.phone %>
</p>

<%= link_to 'Edit', edit_management_path(@management) %> |
<%= link_to 'Back', managements_path %>